# Generated by Django 4.2.3 on 2023-07-16 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SportsCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sport", models.CharField(max_length=100)),
                ("player", models.CharField(max_length=100)),
                ("product", models.CharField(max_length=100)),
                ("variation", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(default=1)),
                ("picture", models.ImageField(upload_to="card_pictures")),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TagCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collection.sportscard",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="collection.tag"
                    ),
                ),
            ],
            options={"unique_together": {("tag", "card")},},
        ),
        migrations.AddField(
            model_name="tag",
            name="cards",
            field=models.ManyToManyField(
                through="collection.TagCard", to="collection.sportscard"
            ),
        ),
    ]
